### ISSUE TITLE
URL in email body should be a <a href> ?

### ISSUE THREAD

**Issue by simonkincaidkintronix** [aerni/statamic-social-links#2]
Hi,

Great plugin

Just an improvement on the email ... 

1. There is a fullstop after the URL which means anyone trying to copy and paste the link may inadvertently copy it, and break the resulting pasted link.
2. The URL comes up as plaintext (tested in OsX mail only though) when it should really be a link that can be clicked ?

What do you think?

**Comment by simonkincaidkintronix** [comment]
I've looked into this a bit more, even addthis.com uses plaintext links, so I just think removing the full stop, and potentially adding a prefix as well as suffix instead of just body?

**Comment by aerni** [comment]
> 1. There is a fullstop after the URL which means anyone trying to copy and paste the link may inadvertently copy it, and break the resulting pasted link.
I don't quite understand what you mean by this. Please explain with example code.

>2. The URL comes up as plaintext (tested in OsX mail only though) when it should really be a link that can be clicked ?
You can't make that a link. Only plaintext is possible. A lot of modern email clients are smart enough and will convert it to a clickable link anyways.

> ... and potentially adding a prefix as well as suffix instead of just body?
What do you mean by prefix and suffix? Where should this go? What do you want to do with it?

**Comment by aerni** [comment]
I updated the behavior of the email channel.

The `url` will be placed in the body of the email by default. You can customize the email body text by using the `body` parameter. Note, that this will override the default body text that includes the `url`. You will have to manually add the `url` in the `body` parameter like so:

```html
{{ social_links:mail body="I want to share this great site with you: {permalink}" }}
```
