### ISSUE TITLE
LinkedIn company page support

### ISSUE THREAD

**Issue by generator85** [aerni/statamic-social-links#9]
Right now it seems that the plugin only supports support personal LinkedIn pages, it would be great if there was a `company` parameter to allow linking to company pages (i.e. https://www.linkedin.com/company/statamic/).

**Comment by aerni** [comment]
Company pages are supported by setting `type="company"` on the tag.

https://github.com/aerni/statamic-social-links/blob/ca61814a1826f659bd5895e64764bf26b2ac83ee/src/Channels/LinkedIn.php#L14-L20

**Comment by generator85** [comment]
Ah great, thanks! Maybe an idea to add this to the readme?
